In [2]:
import netCDF4 as nc
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

all_file = 'da_hydro_AprMar_r.1-2000_d.05-Jan-2018.nc'
all_data = nc.Dataset(all_file)

all_data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    history_of_appended_files: Wed Mar 14 16:04:33 2018: Appended file ./input-recon/cesm_latlon.nc had following "history" attribute:
Thu Nov 30 14:56:30 2017: ncks -A -v lat,lon b.e11.BLMTRC5CN.f19_g16.010.cam.h0.TREFHT.085001-184912.nc /home/nsteiger/MATLAB/hydro-recon/cesm_latlon.nc

    author: Nathan Steiger, LDEO Columbia University, Mar 2018
    history: Wed Mar 14 16:04:45 2018: ncatted -O --glb_att_add citation=https://doi.org/10.5281/zenodo.1154913 da_hydro_AprMar_r.1-2000_d.05-Jan-2018.nc
Wed Mar 14 16:04:45 2018: ncatted -O --glb_att_add author=Nathan Steiger, LDEO Columbia University, Mar 2018 da_hydro_AprMar_r.1-2000_d.05-Jan-2018.nc
Wed Mar 14 16:04:33 2018: ncks -A -v lat,lon ./input-recon/cesm_latlon.nc da_hydro_AprMar_r.1-2000_d.05-Jan-2018.nc
    NCO: "4.6.2"
    citation: https://doi.org/10.5281/zenodo.1154913
    dimensions(sizes): lat(96), lon(144), time(2000), tmon(24000), prctl(3)
    variables(dimensions): float64 lat(lat), float64 lon(lon), float64 time(time), float64 tmon(tmon), float64 tas_mn(time, lat, lon), float64 tas_sg(time, lat, lon), float64 tas_pc(prctl, time, lat, lon), float64 pdsi_mn(time, lat, lon), float64 pdsi_sg(time, lat, lon), float64 pdsi_pc(prctl, time, lat, lon), float64 spei_mn(time, lat, lon), float64 spei_sg(time, lat, lon), float64 spei_pc(prctl, time, lat, lon), float64 Nino_12_mn(tmon), float64 Nino_12_sg(tmon), float64 Nino_12_pc(prctl, tmon), float64 Nino_3_mn(tmon), float64 Nino_3_sg(tmon), float64 Nino_3_pc(prctl, tmon), float64 Nino_3.4_mn(tmon), float64 Nino_3.4_sg(tmon), float64 Nino_3.4_pc(prctl, tmon), float64 Nino_4_mn(tmon), float64 Nino_4_sg(tmon), float64 Nino_4_pc(prctl, tmon), float64 PacDelSST_mn(tmon), float64 PacDelSST_sg(tmon), float64 PacDelSST_pc(prctl, tmon), float64 Atl_mn(time), float64 Atl_sg(time), float64 Atl_pc(prctl, time), float64 Pac130_mn(time), float64 Pac130_sg(time), float64 Pac130_pc(prctl, time), float64 Pac160_mn(time), float64 Pac160_sg(time), float64 Pac160_pc(prctl, time), float64 EPac_mn(time), float64 EPac_sg(time), float64 EPac_pc(prctl, time), float64 WPac_mn(time), float64 WPac_sg(time), float64 WPac_pc(prctl, time), float64 SAsia_mn(time), float64 SAsia_sg(time), float64 SAsia_pc(prctl, time), float64 IndOcn_mn(time), float64 IndOcn_sg(time), float64 IndOcn_pc(prctl, time), float64 SAmer_mn(time), float64 SAmer_sg(time), float64 SAmer_pc(prctl, time), float64 Ind_mn(time), float64 Ind_sg(time), float64 Ind_pc(prctl, time), float64 Afr_mn(time), float64 Afr_sg(time), float64 Afr_pc(prctl, time), float64 EAfr_mn(time), float64 EAfr_sg(time), float64 EAfr_pc(prctl, time), float64 gmt_mn(time), float64 gmt_sg(time), float64 gmt_pc(prctl, time), float64 amo_mn(time), float64 amo_sg(time), float64 amo_pc(prctl, time)
    groups:

In [2]:
print(all_data['time'])
print('\n=========================================\n')
print(all_data['lat'])
print('\n=========================================\n')
print(all_data['lon'])
print('\n=========================================\n')
print(all_data['tmon'])

<class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    long_name: Years CE
    units: Annual mean starting from April to the next calendar year March
unlimited dimensions:
current shape = (2000,)
filling on, default _FillValue of 9.969209968386869e+36 used

=========================================

<class 'netCDF4._netCDF4.Variable'>
float64 lat(lat)
    long_name: latitude
    units: degrees_north
unlimited dimensions:
current shape = (96,)
filling on, default _FillValue of 9.969209968386869e+36 used

=========================================

<class 'netCDF4._netCDF4.Variable'>
float64 lon(lon)
    long_name: longitude
    units: degrees_east
unlimited dimensions:
current shape = (144,)
filling on, default _FillValue of 9.969209968386869e+36 used

=========================================

<class 'netCDF4._netCDF4.Variable'>
float64 tmon(tmon)
    long_name: Fractional years CE
    units: Monthly mean
unlimited dimensions:
current shape = (24000,)
filling on, default _FillValue of 9.969209968386869e+36 used

In [10]:
print(all_data['time'][:])  #goes from 1 to 2000
print('\n=========================================\n')
print(all_data['lat'][:])   #goes up in steps of 1.89473685 (?? why ??) from -90 to 90
print('\n=========================================\n')
print(all_data['lon'][:])   #goes up in steps of 2.5 from 0 to 357.5
print('\n=========================================\n')
print(all_data['tmon'][:])    #goes up in steps of 0.08333333, or, 1/12 to indicate month

[1.000e+00 2.000e+00 3.000e+00 ... 1.998e+03 1.999e+03 2.000e+03]

=========================================

[-90.         -88.10526316 -86.21052632 -84.31578947 -82.42105263
 -80.52631579 -78.63157895 -76.73684211 -74.84210526 -72.94736842
 -71.05263158 -69.15789474 -67.26315789 -65.36842105 -63.47368421
 -61.57894737 -59.68421053 -57.78947368 -55.89473684 -54.
 -52.10526316 -50.21052632 -48.31578947 -46.42105263 -44.52631579
 -42.63157895 -40.73684211 -38.84210526 -36.94736842 -35.05263158
 -33.15789474 -31.26315789 -29.36842105 -27.47368421 -25.57894737
 -23.68421053 -21.78947368 -19.89473684 -18.         -16.10526316
 -14.21052632 -12.31578947 -10.42105263  -8.52631579  -6.63157895
  -4.73684211  -2.84210526  -0.94736842   0.94736842   2.84210526
   4.73684211   6.63157895   8.52631579  10.42105263  12.31578947
  14.21052632  16.10526316  18.          19.89473684  21.78947368
  23.68421053  25.57894737  27.47368421  29.36842105  31.26315789
  33.15789474  35.05263158  36.94736842  38.84210526  40.73684211
  42.63157895  44.52631579  46.42105263  48.31578947  50.21052632
  52.10526316  54.          55.89473684  57.78947368  59.68421053
  61.57894737  63.47368421  65.36842105  67.26315789  69.15789474
  71.05263158  72.94736842  74.84210526  76.73684211  78.63157895
  80.52631579  82.42105263  84.31578947  86.21052632  88.10526316
  90.        ]

=========================================

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.   27.5
  30.   32.5  35.   37.5  40.   42.5  45.   47.5  50.   52.5  55.   57.5
  60.   62.5  65.   67.5  70.   72.5  75.   77.5  80.   82.5  85.   87.5
  90.   92.5  95.   97.5 100.  102.5 105.  107.5 110.  112.5 115.  117.5
 120.  122.5 125.  127.5 130.  132.5 135.  137.5 140.  142.5 145.  147.5
 150.  152.5 155.  157.5 160.  162.5 165.  167.5 170.  172.5 175.  177.5
 180.  182.5 185.  187.5 190.  192.5 195.  197.5 200.  202.5 205.  207.5
 210.  212.5 215.  217.5 220.  222.5 225.  227.5 230.  232.5 235.  237.5
 240.  242.5 245.  247.5 250.  252.5 255.  257.5 260.  262.5 265.  267.5
 270.  272.5 275.  277.5 280.  282.5 285.  287.5 290.  292.5 295.  297.5
 300.  302.5 305.  307.5 310.  312.5 315.  317.5 320.  322.5 325.  327.5
 330.  332.5 335.  337.5 340.  342.5 345.  347.5 350.  352.5 355.  357.5]

=========================================

[1.00000000e+00 1.08333333e+00 1.16666667e+00 ... 2.00075000e+03
 2.00083333e+03 2.00091667e+03]

In [11]:
print(all_data['pdsi_mn'])
print('\n=========================================\n')
print(all_data['pdsi_sg'])
print('\n=========================================\n')
print(all_data['pdsi_pc'])

<class 'netCDF4._netCDF4.Variable'>
float64 pdsi_mn(time, lat, lon)
    _FillValue: nan
    long_name: PDSI (land only) (reconstruction mean)
    units: Standardized units of relative dry and wet
    missing_value: nan
unlimited dimensions:
current shape = (2000, 96, 144)
filling on

=========================================

<class 'netCDF4._netCDF4.Variable'>
float64 pdsi_sg(time, lat, lon)
    _FillValue: nan
    long_name: PDSI (land only) (1 standard deviation of ensemble)
    units: Standardized units of relative dry and wet
    missing_value: nan
unlimited dimensions:
current shape = (2000, 96, 144)
filling on

=========================================

<class 'netCDF4._netCDF4.Variable'>
float64 pdsi_pc(prctl, time, lat, lon)
    _FillValue: nan
    long_name: PDSI (land only) (ensemble percentiles: 5th, 50th, 95th)
    units: Standardized units of relative dry and wet
    missing_value: nan
unlimited dimensions:
current shape = (3, 2000, 96, 144)
filling on

In [63]:
all_data['pdsi_pc']

<class 'netCDF4._netCDF4.Variable'>
float64 pdsi_pc(prctl, time, lat, lon)
    _FillValue: nan
    long_name: PDSI (land only) (ensemble percentiles: 5th, 50th, 95th)
    units: Standardized units of relative dry and wet
    missing_value: nan
unlimited dimensions:
current shape = (3, 2000, 96, 144)
filling on

In [68]:
all_data['time'][1999:2000]
# print(list(range(1900, 2001)))

masked_array(data=[2000.],
             mask=False,
       fill_value=1e+20)

In [26]:
# FUNCTIONS

# name is a string, lat and lons are tuples indicating the start and stop point
# gets data for all mcruns
# both the prate and pdsi params go (time, mcrun, lat, lon)
def get_locale_pdsi_df(name, lat, lon, time_range):
    print(f'Converting PHYDA pdsi data for the locale {name}...')

    std_array = all_data['pdsi_sg'][time_range[0] - 1: time_range[1], lat[0]:lat[1], lon[0]:lon[1]]
    std_array = std_array.reshape(-1)

    prctl_5_array = all_data['pdsi_pc'][0, time_range[0] - 1: time_range[1], lat[0]:lat[1], lon[0]:lon[1]]
    prctl_5_array = prctl_5_array.reshape(-1)

    prctl_50_array = all_data['pdsi_pc'][1, time_range[0] - 1: time_range[1], lat[0]:lat[1], lon[0]:lon[1]]
    prctl_50_array = prctl_50_array.reshape(-1)

    prctl_95_array = all_data['pdsi_pc'][2, time_range[0] - 1: time_range[1], lat[0]:lat[1], lon[0]:lon[1]]
    prctl_95_array = prctl_95_array.reshape(-1)

    mean_array = all_data['pdsi_mn'][time_range[0] - 1: time_range[1], lat[0]:lat[1], lon[0]:lon[1]]
    mean_array = mean_array.reshape(-1)

    pdsi_dict = {
        'Year': list(range(time_range[0], time_range[1] + 1)),
        'PDSI 1 STD': std_array,
        'PDSI 5th PRCTL': prctl_5_array,
        'PDSI 50th PRCTL': prctl_50_array,
        'PDSI 95th PRCTL': prctl_95_array,
        'PDSI Mean': mean_array
    }

    pdsi_df = pd.DataFrame(pdsi_dict)

    print('Finished converting PHYDA data. Resultant dataframe is:')
    print(pdsi_df)

    return pdsi_df


# get pdsi dfs from lists containing data (assume all the same length)
def get_pdsi_dfs_from_locale_list(name_list, lat_list, lon_list, time_range=(1700, 2000)):

    locale_dfs = []

    for locale in range(len(name_list)):
        locale_pdsi = get_locale_pdsi_df(name_list[locale], lat_list[locale], lon_list[locale], time_range)
        locale_dfs.append(locale_pdsi)

    return locale_dfs

In [8]:
print("Time range:")
#print(prate_data['time'][1700:2001])
# print('\n=================== MPWAPWA ======================\n')
# print("Lat range: ")
# print(all_data['lat'][44:45])
# print("Lon range: ")
# print(all_data['lon'][15:16])
# print('\n=================== Ujiji ======================\n')
# print("Lat range: ")
# print(all_data['lat'][45:46])
# print("Lon range: ")
# print(all_data['lon'][12:13])
print('\n=================== Tabora ======================\n')
print("Lat range: ")
print(all_data['lat'][45:46])
print("Lon range: ")
print(all_data['lon'][13:14])

# Gwyn Request
# print('\n=================== Antananarivo ======================\n')
# print("Lat range: ")
# print(all_data['lat'][38:39])
# print("Lon range: ")
# print(all_data['lon'][19:20])

Time range:

=================== Tabora ======================

Lat range:
[-4.73684211]
Lon range:
[32.5]

In [9]:
# Locales (lat (N), lon (E):
# Mpwapwa: -6.35, 36.48
# Ujiji: -4.91, 29.68
# # # Tabora: -5.02, 32.83

# Gwyn Request
# Antananarivo: 18.8792° S, 47.5079° E (-18.933333, 47.516667)

# East Africa Locales
# locale_names = ['Mpwapwa', 'Ujiji']
# locale_filenames = ['mpwapwa_all_pdsi','ujiji_all_pdsi']   #2 csv files for each location
# locale_lats = [(44, 45), (45, 46)]
# locale_lons = [(15, 16), (12, 13)]

# East Africa Locales
# locale_names = ['Tabora']
# locale_filenames = ['tabora_all_pdsi']   #2 csv files for each location
# locale_lats = [(45, 46)]
# locale_lons = [(13, 14)]

# Gwyn Request
# locale_names = ['Antananarivo']
# locale_filenames = ['antananarivo_all_pdsi']
# locale_lats = [(38, 39)]
# locale_lons = [(19, 20)]

In [ ]:
# entirety of China

# print(all_data['lat'][58:77])       # north
# print('\n=========================================\n')
# print(all_data['lon'][31:54])       # east

# china coord points (lon, lat)
# 110, 21.79 --> 110, 42.63         # d
# 112.5, 21.79 --> 112.5, 44.53     # d
# 115, 23.68 --> 115, 44.53         # d
# 117.5, 23.68 --> 117.5, 46.42     # d
# 120, 25.58 --> 120, 52.10         # d
# 122.5, 29.37 --> 122.5, 54        # d
# 125, 40.64 --> 125, 52.10         # d
# 127.5, 42.63 --> 127.5, 52.10     # d
# 130, 42.63 --> 130, 52.10         # d
# 132.5, 46.42 --> 132.5, 48.31     #
# 107.5, 21.79 --> 107.5, 42.63     # d
# 105, 23.68 --> 105, 42.63         # d
# 102.5, 23.68 --> 102.5, 42.63     # d
# 100, 21.79 --> 100, 42.63         # d
# 97.5, 25.58 --> 97.5, 42.63       # d
# 95, 29.37 --> 95, 44.53           # d
# 92.5, 29.37 --> 92.5, 44.53       # d
# 90, 29.37 --> 90, 46.42           # d
# 87.5, 29.36 --> 87.5, 48.31       # d
# 85, 29.37 --> 85, 46.42           # d
# 82.5, 31.26 --> 82.5, 46.42       # d
# 80, 31.26 --> 80, 44.53           # d
# 77.5, 35.05 --> 77.5, 40.74       # d

# all_lons = [(31, 32), (32, 33), (33, 34), (34, 35), (35, 36), (36, 37), (37, 38), (38, 39), (39, 40), (40, 41), (41, 42), (42, 43), (43, 44), (44, 45), (45, 46), (46, 47), (47, 48), (48, 49), (49, 50), (50, 51), (51, 52), (52, 53), (53, 54)]

# lats_per_lon = [(66, 70), (64, 72), (64, 73), (63, 73), (63, 74), (63, 73), (63, 72), (63, 72), (61, 71), (59, 71), (60, 71), (60, 71), (59, 71), (59, 71), (59, 72), (60, 72), (60, 73), (61, 76), (63, 77), (69, 76), (70, 76), (70, 76), (72, 74)]

In [10]:
print("Lon range: ")
print(all_data['lon'][7:8])
print("Lat range: ")
print(all_data['lat'][29:30])

dat = all_data['pdsi_mn'][1750:1775, 29:30, 7:8]
print(dat)

Lon range:
[17.5]
Lat range:
[-35.05263158]
[[[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]

 [[--]]]

In [23]:
# south africa
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 17.5  -27.5 --> -35   (7:8, 29:34)
# 20    -25.5 --> -35   (8:9, 29:35)
# 22.5  -25.5 --> -33   (9:10, 30:35)
# 25    -25.5 --> -33   (10:11, 30:35)
# 27.5  -23.7 --> -33   (11:12, 30:36)
# 30    -21.8 --> -31.3 (12:13, 31:37)
# 32.5  -23.7 --> -27.5 (13:14, 33:36)


all_lons = [(7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14)]
lats_per_lon = [(29, 34), (29, 35), (30, 35), (30, 35), (30, 36), (31, 37), (33, 36)]

In [62]:
# entirety of east africa, inclusive coordinates
# Tanzania, Kenya, Uganda, Burundi, and Rwanda

# tanzania
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 30    -5    --> -8.5  (12:13, 43:46)
# 32.5  -1    --> -8.5  (13:14, 43:48)
# 35    -1    --> -12   (14:15, 41:48)
# 37.5  -3    --> -11   (15:16, 41:47)
# 40    -4    --> -10   (16:17, 42:47)

# all_lons = [(12, 13), (13, 14), (14, 15), (15, 16), (16, 17)]
# lats_per_lon = [(43, 46), (43, 48), (41, 48), (41, 47), (42, 47)]

# kenya
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 35    5     --> -1    (14:15, 47:51)
# 37.5  5     --> -3    (15:16, 46:51)
# 40    3     --> -5    (16:17, 45:50)

# all_lons = [(14, 15), (15, 16), (16, 17)]
# lats_per_lon = [(47, 51), (46, 51), (45, 50)]

# uganda
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 30    3     --> -1    (12:13, 47:50)
# 32.5  3     --> -1    (13:14, 47:50)

# all_lons = [(12, 13), (13, 14)]
# lats_per_lon = [(47, 50), (47, 50)]

# burundi
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 30    -3     --> -    (12:13, 46:47)

# all_lons = [(12, 13)]
# lats_per_lon = [(46, 47)]

# rwanda
# lon   lat1  --> lat2  (lon_index, lat1:lat2)
# 30    -1     --> -    (12:13, 47:48)

# all_lons = [(12, 13)]
# lats_per_lon = [(47, 48)]

In [24]:
locale_lats = []
locale_lons = []
locale_names = []
locale_filenames = []
time_range = (500, 2000)

for i in range(len(all_lons)):
    lat_range = lats_per_lon[i]
    for lat in range(lat_range[0], lat_range[1]):
        locale_lats.append((lat, lat + 1))
        locale_lons.append(all_lons[i])
        name = f'southafrica_lat_{all_data["lat"][lat: lat + 1][0]}_lon_{all_data["lon"][all_lons[i][0] : all_lons[i][1]][0]}'
        locale_names.append(name)
        locale_filenames.append(name)

print(locale_lats)
print('\n=========================================\n')
print(locale_lons)
print('\n=========================================\n')
print(locale_names)
print('\n=========================================\n')
print(locale_filenames)

[(29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35), (35, 36), (31, 32), (32, 33), (33, 34), (34, 35), (35, 36), (36, 37), (33, 34), (34, 35), (35, 36)]

=========================================

[(7, 8), (7, 8), (7, 8), (7, 8), (7, 8), (8, 9), (8, 9), (8, 9), (8, 9), (8, 9), (8, 9), (9, 10), (9, 10), (9, 10), (9, 10), (9, 10), (10, 11), (10, 11), (10, 11), (10, 11), (10, 11), (11, 12), (11, 12), (11, 12), (11, 12), (11, 12), (11, 12), (12, 13), (12, 13), (12, 13), (12, 13), (12, 13), (12, 13), (13, 14), (13, 14), (13, 14)]

=========================================

['southafrica_lat_-35.05263157894737_lon_17.5', 'southafrica_lat_-33.15789473684211_lon_17.5', 'southafrica_lat_-31.263157894736842_lon_17.5', 'southafrica_lat_-29.368421052631582_lon_17.5', 'southafrica_lat_-27.473684210526322_lon_17.5', 'southafrica_lat_-35.05263157894737_lon_20.0', 'southafrica_lat_-33.15789473684211_lon_20.0', 'southafrica_lat_-31.263157894736842_lon_20.0', 'southafrica_lat_-29.368421052631582_lon_20.0', 'southafrica_lat_-27.473684210526322_lon_20.0', 'southafrica_lat_-25.578947368421055_lon_20.0', 'southafrica_lat_-33.15789473684211_lon_22.5', 'southafrica_lat_-31.263157894736842_lon_22.5', 'southafrica_lat_-29.368421052631582_lon_22.5', 'southafrica_lat_-27.473684210526322_lon_22.5', 'southafrica_lat_-25.578947368421055_lon_22.5', 'southafrica_lat_-33.15789473684211_lon_25.0', 'southafrica_lat_-31.263157894736842_lon_25.0', 'southafrica_lat_-29.368421052631582_lon_25.0', 'southafrica_lat_-27.473684210526322_lon_25.0', 'southafrica_lat_-25.578947368421055_lon_25.0', 'southafrica_lat_-33.15789473684211_lon_27.5', 'southafrica_lat_-31.263157894736842_lon_27.5', 'southafrica_lat_-29.368421052631582_lon_27.5', 'southafrica_lat_-27.473684210526322_lon_27.5', 'southafrica_lat_-25.578947368421055_lon_27.5', 'southafrica_lat_-23.684210526315795_lon_27.5', 'southafrica_lat_-31.263157894736842_lon_30.0', 'southafrica_lat_-29.368421052631582_lon_30.0', 'southafrica_lat_-27.473684210526322_lon_30.0', 'southafrica_lat_-25.578947368421055_lon_30.0', 'southafrica_lat_-23.684210526315795_lon_30.0', 'southafrica_lat_-21.789473684210535_lon_30.0', 'southafrica_lat_-27.473684210526322_lon_32.5', 'southafrica_lat_-25.578947368421055_lon_32.5', 'southafrica_lat_-23.684210526315795_lon_32.5']

=========================================

['southafrica_lat_-35.05263157894737_lon_17.5', 'southafrica_lat_-33.15789473684211_lon_17.5', 'southafrica_lat_-31.263157894736842_lon_17.5', 'southafrica_lat_-29.368421052631582_lon_17.5', 'southafrica_lat_-27.473684210526322_lon_17.5', 'southafrica_lat_-35.05263157894737_lon_20.0', 'southafrica_lat_-33.15789473684211_lon_20.0', 'southafrica_lat_-31.263157894736842_lon_20.0', 'southafrica_lat_-29.368421052631582_lon_20.0', 'southafrica_lat_-27.473684210526322_lon_20.0', 'southafrica_lat_-25.578947368421055_lon_20.0', 'southafrica_lat_-33.15789473684211_lon_22.5', 'southafrica_lat_-31.263157894736842_lon_22.5', 'southafrica_lat_-29.368421052631582_lon_22.5', 'southafrica_lat_-27.473684210526322_lon_22.5', 'southafrica_lat_-25.578947368421055_lon_22.5', 'southafrica_lat_-33.15789473684211_lon_25.0', 'southafrica_lat_-31.263157894736842_lon_25.0', 'southafrica_lat_-29.368421052631582_lon_25.0', 'southafrica_lat_-27.473684210526322_lon_25.0', 'southafrica_lat_-25.578947368421055_lon_25.0', 'southafrica_lat_-33.15789473684211_lon_27.5', 'southafrica_lat_-31.263157894736842_lon_27.5', 'southafrica_lat_-29.368421052631582_lon_27.5', 'southafrica_lat_-27.473684210526322_lon_27.5', 'southafrica_lat_-25.578947368421055_lon_27.5', 'southafrica_lat_-23.684210526315795_lon_27.5', 'southafrica_lat_-31.263157894736842_lon_30.0', 'southafrica_lat_-29.368421052631582_lon_30.0', 'southafrica_lat_-27.473684210526322_lon_30.0', 'southafrica_lat_-25.578947368421055_lon_30.0', 'southafrica_lat_-23.684210526315795_lon_30.0', 'southafrica_lat_-21.789473684210535_lon_30.0', 'southafrica_lat_-27.473684210526322_lon_32.5', 'southafrica_lat_-25.578947368421055_lon_32.5', 'southafrica_lat_-23.684210526315795_lon_32.5']

In [27]:
# GET DFs

locale_dfs = get_pdsi_dfs_from_locale_list(locale_names, locale_lats, locale_lons, time_range=time_range)

Converting PHYDA pdsi data for the locale southafrica_lat_-35.05263157894737_lon_17.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500         NaN             NaN              NaN              NaN
1      501         NaN             NaN              NaN              NaN
2      502         NaN             NaN              NaN              NaN
3      503         NaN             NaN              NaN              NaN
4      504         NaN             NaN              NaN              NaN
...    ...         ...             ...              ...              ...
1496  1996         NaN             NaN              NaN              NaN
1497  1997         NaN             NaN              NaN              NaN
1498  1998         NaN             NaN              NaN              NaN
1499  1999         NaN             NaN              NaN              NaN
1500  2000         NaN             NaN              NaN              NaN

      PDSI Mean
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
...         ...
1496        NaN
1497        NaN
1498        NaN
1499        NaN
1500        NaN

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-33.15789473684211_lon_17.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.921302       -2.771476        -0.470480         3.515080
1      501    1.920292       -2.904467        -0.594508         3.399506
2      502    1.921540       -2.703240        -0.401243         3.578033
3      503    1.920474       -2.076718         0.233780         4.227090
4      504    1.920359       -2.005712         0.304204         4.298375
...    ...         ...             ...              ...              ...
1496  1996    1.839984       -4.125393        -1.921748         1.931767
1497  1997    1.842336       -2.903162        -0.664857         3.207146
1498  1998    1.849120       -5.015491        -2.763087         1.165290
1499  1999    1.853113       -3.615373        -1.352646         2.571594
1500  2000    1.858487       -3.735666        -1.453561         2.459113

      PDSI Mean
0     -0.227408
1     -0.352958
2     -0.158939
3      0.473849
4      0.545497
...         ...
1496  -1.638827
1497  -0.392819
1498  -2.486265
1499  -1.073301
1500  -1.183068

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-31.263157894736842_lon_17.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.560677       -2.703667        -0.524623         2.438311
1      501    1.558531       -2.657781        -0.490246         2.457027
2      502    1.560794       -2.696597        -0.519730         2.441757
3      503    1.558579       -1.987212         0.179722         3.125373
4      504    1.558570       -1.841954         0.325391         3.272451
...    ...         ...             ...              ...              ...
1496  1996    1.477777       -2.826561        -0.796246         1.995809
1497  1997    1.479956       -2.083513        -0.050606         2.741433
1498  1998    1.485103       -3.963836        -1.902284         0.912474
1499  1999    1.490184       -3.131505        -1.074154         1.748501
1500  2000    1.494063       -3.126067        -1.077475         1.734954

      PDSI Mean
0     -0.412020
1     -0.386449
2     -0.406325
3      0.283413
4      0.429364
...         ...
1496  -0.676353
1497   0.069953
1498  -1.787157
1499  -0.948901
1500  -0.955705

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-29.368421052631582_lon_17.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.458867       -2.831789        -0.730262         2.214405
1      501    1.456176       -2.807249        -0.709763         2.217034
2      502    1.458870       -2.864131        -0.762166         2.182155
3      503    1.456186       -2.351768        -0.254938         2.670485
4      504    1.456186       -2.058448         0.039129         2.966030
...    ...         ...             ...              ...              ...
1496  1996    1.385179       -2.469497        -0.479688         2.376809
1497  1997    1.389465       -1.898132         0.077476         2.939803
1498  1998    1.394454       -3.767652        -1.746952         1.103578
1499  1999    1.399669       -2.823578        -0.809165         2.053042
1500  2000    1.401462       -2.358222        -0.344335         2.536277

      PDSI Mean
0     -0.659698
1     -0.643400
2     -0.691747
3     -0.188460
4      0.105479
...         ...
1496  -0.395926
1497   0.157792
1498  -1.681584
1499  -0.740195
1500  -0.270229

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-27.473684210526322_lon_17.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.546658       -3.054337        -0.915645         2.093400
1      501    1.544468       -2.986291        -0.867205         2.140804
2      502    1.546697       -3.045860        -0.907220         2.101370
3      503    1.544511       -2.513535        -0.393787         2.613155
4      504    1.544469       -2.231687        -0.112589         2.895467
...    ...         ...             ...              ...              ...
1496  1996    1.467835       -1.700744         0.279918         3.179043
1497  1997    1.470560       -1.729912         0.244689         3.169691
1498  1998    1.477198       -3.540177        -1.578652         1.337303
1499  1999    1.482679       -2.705810        -0.727910         2.176621
1500  2000    1.484726       -2.007648        -0.022738         2.880615

      PDSI Mean
0     -0.800279
1     -0.752925
2     -0.791686
3     -0.280876
4      0.001751
...         ...
1496   0.424573
1497   0.394538
1498  -1.426060
1499  -0.579790
1500   0.128028

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-35.05263157894737_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.301264       -2.012554        -0.115293         2.396857
1      501    1.300556       -2.173687        -0.276073         2.221439
2      502    1.301620       -1.940328        -0.041386         2.466916
3      503    1.300810       -2.048555        -0.149744         2.348452
4      504    1.300649       -2.037007        -0.138752         2.358407
...    ...         ...             ...              ...              ...
1496  1996    1.254541       -2.420881        -0.601216         1.823294
1497  1997    1.255382       -2.682366        -0.859482         1.559637
1498  1998    1.259025       -2.883318        -1.044626         1.370531
1499  1999    1.261328       -2.153539        -0.307325         2.101468
1500  2000    1.263792       -2.396184        -0.549041         1.861958

      PDSI Mean
0     -0.061443
1     -0.225321
2      0.010114
3     -0.099529
4     -0.088412
...         ...
1496  -0.538881
1497  -0.800424
1498  -0.988323
1499  -0.248884
1500  -0.502269

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-33.15789473684211_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.769988       -3.122789        -0.616599         2.721782
1      501    1.767909       -3.189970        -0.679075         2.675369
2      502    1.770026       -3.104851        -0.597469         2.739743
3      503    1.767972       -2.589293        -0.079383         3.276685
4      504    1.767977       -2.338263         0.173072         3.527467
...    ...         ...             ...              ...              ...
1496  1996    1.678610       -3.138740        -0.930874         2.333445
1497  1997    1.681944       -2.277216        -0.052793         3.219093
1498  1998    1.687394       -4.498038        -2.256270         1.035710
1499  1999    1.692338       -2.892616        -0.655721         2.641067
1500  2000    1.696503       -2.863156        -0.607458         2.685378

      PDSI Mean
0     -0.456549
1     -0.511895
2     -0.438438
3      0.088135
4      0.339729
...         ...
1496  -0.741422
1497   0.134811
1498  -2.074218
1499  -0.467113
1500  -0.419816

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-31.263157894736842_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.618114       -3.071568        -0.754021         2.384634
1      501    1.615244       -2.992371        -0.690030         2.458054
2      502    1.618127       -3.073683        -0.756300         2.382187
3      503    1.615288       -2.481827        -0.179502         2.967590
4      504    1.615252       -2.103430         0.199075         3.346872
...    ...         ...             ...              ...              ...
1496  1996    1.522188       -2.096149         0.039574         3.151685
1497  1997    1.527794       -1.431787         0.688014         3.813601
1498  1998    1.535192       -3.674883        -1.546611         1.586487
1499  1999    1.541537       -2.718354        -0.561664         2.578744
1500  2000    1.543807       -2.090247         0.057165         3.169563

      PDSI Mean
0     -0.659827
1     -0.580955
2     -0.662420
3     -0.070752
4      0.307960
...         ...
1496   0.186542
1497   0.838969
1498  -1.403031
1499  -0.415208
1500   0.209123

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-29.368421052631582_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.485437       -2.940039        -0.813605         2.194532
1      501    1.482694       -2.881769        -0.762970         2.273329
2      502    1.485478       -2.968902        -0.843149         2.164926
3      503    1.482747       -2.400288        -0.281676         2.755140
4      504    1.482696       -2.086834         0.031983         3.068330
...    ...         ...             ...              ...              ...
1496  1996    1.399197       -1.826280         0.167293         2.952325
1497  1997    1.403001       -1.619336         0.375004         3.142466
1498  1998    1.408648       -3.813883        -1.809755         0.992894
1499  1999    1.413923       -2.691042        -0.670462         2.140394
1500  2000    1.415695       -1.881214         0.137991         2.952343

      PDSI Mean
0     -0.692612
1     -0.634157
2     -0.722268
3     -0.152835
4      0.160828
...         ...
1496   0.330000
1497   0.533754
1498  -1.661504
1499  -0.523709
1500   0.278545

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-27.473684210526322_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.491766       -2.834358        -0.835906         2.031423
1      501    1.489068       -2.681797        -0.684758         2.170440
2      502    1.491804       -2.845849        -0.846178         2.021973
3      503    1.489076       -2.294406        -0.297548         2.558424
4      504    1.489074       -1.954919         0.042146         2.897452
...    ...         ...             ...              ...              ...
1496  1996    1.408211       -1.616651         0.245564         2.984543
1497  1997    1.410856       -1.787626         0.088536         2.821328
1498  1998    1.415825       -3.904291        -1.999799         0.716079
1499  1999    1.420577       -2.632351        -0.739531         1.989612
1500  2000    1.421804       -1.854277         0.067556         2.772389

      PDSI Mean
0     -0.711382
1     -0.566656
2     -0.721255
3     -0.179540
4      0.160311
...         ...
1496   0.375482
1497   0.219941
1498  -1.870928
1499  -0.605428
1500   0.184621

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-25.578947368421055_lon_20.0...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.520188       -2.757469        -0.747393         2.198507
1      501    1.518012       -2.540619        -0.534799         2.414777
2      502    1.520227       -2.835254        -0.824011         2.123357
3      503    1.518014       -2.136074        -0.130122         2.818059
4      504    1.518018       -1.794329         0.211452         3.161026
...    ...         ...             ...              ...              ...
1496  1996    1.443415       -2.061417        -0.111933         2.668904
1497  1997    1.445701       -1.774469         0.156098         2.969346
1498  1998    1.450819       -3.703311        -1.765529         1.092185
1499  1999    1.455438       -2.589183        -0.648623         2.182764
1500  2000    1.456973       -1.691427         0.241644         3.089560

      PDSI Mean
0     -0.592503
1     -0.378056
2     -0.668681
3      0.026340
4      0.368216
...         ...
1496   0.027756
1497   0.308584
1498  -1.609382
1499  -0.496139
1500   0.394593

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-33.15789473684211_lon_22.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.620406       -3.045734        -0.625641         2.402414
1      501    1.617934       -3.042535        -0.649807         2.380357
2      502    1.620425       -3.031198        -0.610571         2.415838
3      503    1.617971       -2.598976        -0.204259         2.825492
4      504    1.617980       -2.224266         0.168657         3.198661
...    ...         ...             ...              ...              ...
1496  1996    1.520599       -2.211933        -0.062701         2.821938
1497  1997    1.527107       -2.044063         0.121046         3.043909
1498  1998    1.534007       -3.850782        -1.722378         1.231592
1499  1999    1.539148       -2.744726        -0.612759         2.372394
1500  2000    1.544407       -2.497332        -0.345702         2.626014

      PDSI Mean
0     -0.559049
1     -0.567102
2     -0.544974
3     -0.122534
4      0.251010
...         ...
1496   0.037103
1497   0.230876
1498  -1.597765
1499  -0.482517
1500  -0.219763

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-31.263157894736842_lon_22.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.606434       -3.289966        -0.697183         2.163930
1      501    1.604195       -3.211146        -0.631478         2.228779
2      502    1.606593       -3.315010        -0.719053         2.145522
3      503    1.604215       -2.647173        -0.069693         2.791982
4      504    1.604200       -2.260339         0.319355         3.179632
...    ...         ...             ...              ...              ...
1496  1996    1.482111       -2.191325         0.149052         2.873195
1497  1997    1.488636       -1.725935         0.582778         3.329090
1498  1998    1.497124       -3.966799        -1.666537         1.100712
1499  1999    1.502530       -2.837706        -0.505063         2.250210
1500  2000    1.506993       -2.117526         0.200662         2.998805

      PDSI Mean
0     -0.649311
1     -0.577440
2     -0.670975
3     -0.014145
4      0.373449
...         ...
1496   0.225773
1497   0.666420
1498  -1.569570
1499  -0.412852
1500   0.306192

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-29.368421052631582_lon_22.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.564290       -3.090846        -0.691024         2.048561
1      501    1.561863       -2.967904        -0.566412         2.183845
2      502    1.564462       -3.162593        -0.762887         1.979473
3      503    1.561861       -2.437544        -0.035689         2.714837
4      504    1.561869       -2.067649         0.333736         3.084166
...    ...         ...             ...              ...              ...
1496  1996    1.450386       -1.947790         0.137378         2.898422
1497  1997    1.454102       -1.742284         0.339916         3.095451
1498  1998    1.460531       -4.103281        -1.990496         0.791678
1499  1999    1.465606       -2.740295        -0.613775         2.194550
1500  2000    1.468544       -1.999417         0.152251         2.951765

      PDSI Mean
0     -0.609094
1     -0.467167
2     -0.680980
3      0.063268
4      0.433039
...         ...
1496   0.247645
1497   0.451778
1498  -1.872731
1499  -0.492266
1500   0.270569

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-27.473684210526322_lon_22.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.615827       -2.768938        -0.612596         2.507326
1      501    1.614888       -2.610677        -0.454536         2.669404
2      502    1.615953       -2.925418        -0.768550         2.351836
3      503    1.614882       -2.199209        -0.044399         3.080724
4      504    1.614900       -1.841662         0.314362         3.438281
...    ...         ...             ...              ...              ...
1496  1996    1.509446       -2.138696        -0.050924         2.924366
1497  1997    1.512059       -1.782230         0.291439         3.254446
1498  1998    1.519448       -3.971596        -1.883402         1.110181
1499  1999    1.525842       -2.570435        -0.485379         2.515877
1500  2000    1.528364       -1.596151         0.500681         3.514831

      PDSI Mean
0     -0.480669
1     -0.322470
2     -0.636492
3      0.088381
4      0.446469
...         ...
1496   0.079168
1497   0.431296
1498  -1.737861
1499  -0.348461
1500   0.645600

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-25.578947368421055_lon_22.5...
Finished converting PHYDA data. Resultant dataframe is:
      Year  PDSI 1 STD  PDSI 5th PRCTL  PDSI 50th PRCTL  PDSI 95th PRCTL  \
0      500    1.593227       -2.872628        -0.586313         2.557802
1      501    1.590942       -2.643533        -0.371427         2.770549
2      502    1.593300       -2.984626        -0.696400         2.446873
3      503    1.590891       -2.225062         0.045572         3.187165
4      504    1.590951       -1.802797         0.469202         3.611263
...    ...         ...             ...              ...              ...
1496  1996    1.491859       -2.547761        -0.510878         2.408977
1497  1997    1.496424       -2.059626        -0.018317         2.929195
1498  1998    1.502229       -3.913141        -1.868741         1.096369
1499  1999    1.507603       -2.706728        -0.655709         2.311294
1500  2000    1.509535       -1.837606         0.224249         3.195795

      PDSI Mean
0     -0.429229
1     -0.208756
2     -0.539090
3      0.207898
4      0.631940
...         ...
1496  -0.347808
1497   0.146122
1498  -1.692765
1499  -0.488463
1500   0.388606

[1501 rows x 6 columns]
Converting PHYDA pdsi data for the locale southafrica_lat_-33.15789473684211_lon_25.0...

In [28]:
# DOWNLOAD FILES

for file in range(len(locale_dfs)):
    filename = f'C:\\Users\\Cecile Dai\\Documents\\Professional\\McGill University\\IOWC\\Other Datasets\\Alternative_Datasets\\PHYDA\\south_africa\\{locale_filenames[file]}.csv'
    locale_dfs[file].to_csv(filename, index=False)